### ISSUE TITLE
Not able to connect to RobotStudio with VS 2017

### ISSUE THREAD

**Issue by mjkoehle** [RobotExMachina/Machina.NET#6]
When trying to connect with RobotStudio using arm.Connect(); fails with:

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'ABB.Robotics.Controllers.PC, Version=6.5.7392.129, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=Machina
  StackTrace:
   at Machina.Drivers.Communication.RobotStudioManager.LoadController(Int32 controllerID)
   at Machina.Drivers.Communication.RobotStudioManager.Connect(Int32 deviceId)
   at Machina.Drivers.DriverABB.ConnectToDevice(Int32 deviceId)
   at Machina.Control.ConnectToDevice(Int32 robotId)
   at testMachinaApp.Program.Main(String[] args) in C:\...\testMachinaApp\Program.cs:line 20

This is with VS 2017, using framework .NET Core 2.1. With VS 2015 and .NET framework 4.6.1, there is no issue.

**Comment by nonoesp** [comment]
Hi @mjkoehle! Sorry to hear.

1. Are you using Machina v0.6.2 or another release version? Or are you building from source?
2. Have you checked if `ABB.Robotics.Controllers.PC.dll` is being copied to the folder from which `Machina.dll` is being loaded in your program?

**Comment by garciadelcastillo** [comment]
Thanks for reporting @mjkoehle.  

Seems like there is a compatibility issue, will look into it. 

However, we are trying to move away from external dependencies in the future. Maybe the way to go in the future is to simply not rely on any other library...

**Comment by mjkoehle** [comment]
Hi Nono,

I've spoken with Jose Luis about this. I believe I tried 6.1 and 6.3 of the
distributions. I made sure  ABB.Robotics.Controllers.PC.dll was in the same
folder as  Machina.dll. I also tried referencing
ABB.Robotics.Controllers.PC.dll directly. I'm running on VS 2015 now, but
if you'd like me to check something, I can go back to 2017.

m

MichaelKoehleArt.com

**Comment by mjkkirschner** [comment]
I think the issue is clear here (of course I am guessing 😉 )- ABB's dlls are not supported in .net core - have you used the .net core checker to see if the assemblies are supposed to work?

https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer
